---
title: "FERRE"
format: html
---

```{r}

#| false
here::i_am("grades-test.Rproj")
library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(vroom)
library(gt)

```

### 1.1 Study organisation

#### Question 1 :  Load the course description file.

```{r}
courses <- vroom(here("data", "courses.csv"))
View(courses)

```
### Question 2 :

```{r}
courses |>
  arrange(course) |>
  gt::gt() |>
  tab_header(title = "Courses Data")

```


###  1.2 Students

####  Question 3

```{r}
students <- vroom(here("data", "students.csv"))
View(students)

```
```{r}
print(class(students$birth_date)) 
```
The variable "birth_date" is of class " `{r} print(class(students$birth_date))` "

```{r}
print(class(students$sex)) 
```

The variable "sex" is of class " `{r} print(class(students$sex))` "
Transformons la variable "sex" en *factor* :

```{r}
students <- students |>
  mutate(sex = factor(sex)) 
print(class(students$sex))
```
The variable "sex" is now of class " `{r} print(class(students$sex))` "
